python3 get_turn.py 10 sp all center
python3 get_turn.py 30 sp all center
python3 get_turn.py 50 sp all center
python3 get_turn.py 10 sp all outskirt
python3 get_turn.py 30 sp all outskirt
python3 get_turn.py 50 sp all outskirt
python3 get_turn.py 10 sp all center_outskirt
python3 get_turn.py 30 sp all center_outskirt
python3 get_turn.py 50 sp all center_outskirt
python3 get_turn.py 10 qp all center
python3 get_turn.py 30 qp all center
python3 get_turn.py 50 qp all center
python3 get_turn.py 10 qp all outskirt
python3 get_turn.py 30 qp all outskirt
python3 get_turn.py 50 qp all outskirt
python3 get_turn.py 10 qp all center_outskirt
python3 get_turn.py 30 qp all center_outskirt
python3 get_turn.py 50 qp all center_outskirt
python3 get_turn.py 10 ftp all center
python3 get_turn.py 30 ftp all center
python3 get_turn.py 50 ftp all center
python3 get_turn.py 10 ftp all outskirt
python3 get_turn.py 30 ftp all outskirt
python3 get_turn.py 50 ftp all outskirt
python3 get_turn.py 10 ftp all center_outskirt
python3 get_turn.py 30 ftp all center_outskirt
python3 get_turn.py 50 ftp all center_outskirt