python3 short_path.py 10 all center
python3 short_path.py 10 all outskirt
python3 short_path.py 10 all center_outskirt
python3 short_path.py 30 all center
python3 short_path.py 30 all outskirt
python3 short_path.py 30 all center_outskirt
python3 short_path.py 50 all center
python3 short_path.py 50 all outskirt
python3 short_path.py 50 all center_outskirt