# python3 get_turn.py 10 sp cities
# python3 get_turn.py 30 sp cities
# python3 get_turn.py 50 sp cities
# python3 get_turn.py 10 qp cities
# python3 get_turn.py 30 qp cities
# python3 get_turn.py 50 qp cities
# python3 get_turn.py 10 ftp cities
# python3 get_turn.py 30 ftp cities
# python3 get_turn.py 50 ftp cities
# python3 get_turn.py 10 smp cities
# python3 get_turn.py 30 smp cities
# python3 get_turn.py 50 smp cities
# python3 get_turn.py 10 sp intl
# python3 get_turn.py 30 sp intl
# python3 get_turn.py 50 sp intl
# python3 get_turn.py 10 qp intl
# python3 get_turn.py 30 qp intl
# python3 get_turn.py 50 qp intl
# python3 get_turn.py 10 ftp intl
# python3 get_turn.py 30 ftp intl
# python3 get_turn.py 50 ftp intl
# python3 get_turn.py 10 smp intl
# python3 get_turn.py 30 smp intl
# python3 get_turn.py 50 smp intl